language: ruby
services:
  - postgresql
rvm:
  - 2.5.1
before_install:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database experteese_test;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - bundle exec rake test