version: '3.5'

services:

  db:
    container_name: ruby-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - psql-data:/var/lib/postgresql/data/

volumes:
    psql-data: