default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: postgres
  timeout: 5000
  reaping_frequency: 30
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
 <<: *default
 database: experteese-dev
 password: <%= Rails.application.secrets[:database][:password] %>

test:
 <<: *default
 database: experteese-test
 password: <%= Rails.application.secrets[:database][:password] %>

production:
 <<: *default
 database: experteese-prod
 password: <%= ENV['DB_PASSWORD'] %>
