default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  username: postgres
  timeout: 5000
  reaping_frequency: 30
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: experteese-dev
  password: postgres

test:
  <<: *default
  database: experteese_test
  password: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>